image: "python:3.7"

before_script:
  - python --version
  - apt-get update -y && apt-get upgrade -y
#  - apt-get install -y libpcap-dev libpq-dev
#  - apt-get install -y rabbitmq-server
#  - service rabbitmq-server start
#  - service rabbitmq-server status
#  - apt-get update && apt-get install -y lsb-release && apt-get clean all
  - wget -qO- https://repos.influxdata.com/influxdb.key | apt-key add -
  - source /etc/os-release
  - echo "deb https://repos.influxdata.com/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/influxdb.list
  - apt-get update && apt-get install influxdb
  - service influxdb start
  - curl -XPOST 'http://localhost:8086/query' --data-urlencode 'q=CREATE DATABASE "telemetry_summary"'
  - ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
  - dpkg-reconfigure --frontend noninteractive tzdata
  - pip install --upgrade pip
  - pip install -r docs/requirements.txt

stages:
  - Static Analysis
  - Test

# pylint:
#  stage: Static Analysis
#  allow_failure: true
#  script:
#    - pylint -d C0301 src/*.py

#mypy:
#  stage: Static Analysis
#  script:
#    - pwd
#    - ls -l
#    - python -m mypy src/*.py
#
flake8:
  stage: Static Analysis
  script:
    - flake8 --max-line-length=120 src/*.py

Telemetry_Summary_Tests:
  stage: Test
  script:
    - pwd
    - ls -l
    - export PYTHONPATH="$PYTHONPATH:."
    - python -c "import sys;print(sys.path)"
    - python -m pytest --cov-report term-missing --cov=src tests/